### PR TITLE
Fixed arbitrary command execution due to inadequate command escaping

### PR DESCRIPTION
**Pull request by Asjidkalam**
Updated files:
- Gemfile
- shell.rb

Fixed using:
- [Terrapin](https://github.com/thoughtbot/terrapin)

### CODE REVIEW

**Review by toufik-airane — APPROVED** [review]
✅ LGTM

Thanks for your contribution. 🔥

**Review by JamieSlome — APPROVED** [review]
Good job - thanks for your contribution! 🥇

**Comment by huntr-helper** [comment]
Congratulations @Asjidkalam - you are the successful huntr!
Thank you for submitting your fix - we have approved your pull request and will merge your commits into our master branch. 
If you have any questions, please respond in the comments section. Your bounty is on its way - keep hunting.

**Comment by Asjidkalam** [comment]
Thankyou! :heart:

**Pull request merged**
